### ISSUE TITLE
Manage connections properly

### ISSUE THREAD

**Issue by anxolerd** [evolving-cowboys/queensman#6]
# Problem

Currently connection state is not managed, thus if it breaks, the whole application breaks. We need to manage connections state trying to reconnect if it is closed.

# TODO

- [ ] Manage connection timeouts: drop connection if server does not respond in some time interval
- [ ] Manage connection failures --- try to re-establish the connection before request if connection is closed
- [ ] Display connection status in the UI
