### ISSUE TITLE
Implement request introspection

### ISSUE THREAD

**Issue by anxolerd** [evolving-cowboys/queensman#8]
# Problem

Currently user have no idea of what is inside the proto file and which data type should be in request. We need to give them hints about it

# TODO

- [ ] Show user the type of request/response of specific call
- [ ] Assist user with types when they write a request
- [ ] Validate request for proper data types
- [ ] Highlight parts of the response (semantic highlighting based on response types)
